# Config relating to the Lazygit UI
gui:
  # How the window is split when in half screen mode (i.e. after hitting '+' once).
  # Possible values:
  # - 'left': split the window horizontally (side panel on the left, main view on the right)
  # - 'top': split the window vertically (side panel on top, main view below)
  enlargedSideViewLocation: top

  # Format used when displaying time e.g. commit time.
  # Uses Go's time format syntax: https://pkg.go.dev/time#Time.Format
  timeFormat: _2 Jan

  # Format used when displaying time if the time is less than 24 hours ago.
  # Uses Go's time format syntax: https://pkg.go.dev/time#Time.Format
  shortTimeFormat: 15:04

  # If true, show the '5 of 20' footer at the bottom of list views
  showListFooter: false

  # If true, show a random tip in the command log when Lazygit starts
  showRandomTip: false

  # If true, show the command log
  showCommandLog: true

  # Height of the command log view
  commandLogSize: 4

  # If true, show the bottom line that contains keybinding info and useful buttons. If false, this line will be hidden except to display a loader for an in-progress action.
  showBottomLine: false

  # If true, show jump-to-window keybindings in window titles.
  showPanelJumps: false

  # Default size for focused window. Window size can be changed from within Lazygit with '+' and '_' (but this won't change the default).
  # One of: 'normal' (default) | 'half' | 'full'
  windowSize: normal

  # Status panel view.
  # One of 'dashboard' (default) | 'allBranchesLog'
  statusPanelView: allBranchesLog
